export HUAWEI_MODBUS_HOST=$2
export HUAWEI_MODBUS_PORT=502
export HUAWEI_MODBUS_DEVICE_ID_SECONDARY=1
export HUAWEI_MODBUS_MQTT_TOPIC_PRIMARY="$1telemetry/inv_primary"
export HUAWEI_MODBUS_MQTT_TOPIC_SECONDARY="$1telemetry/inv_secondary"
export HUAWEI_MODBUS_MQTT_USER="$1"
export HUAWEI_MODBUS_MQTT_PASSWORD=""
export HUAWEI_MODBUS_MQTT_BROKER=""
export HUAWEI_MODBUS_DEBUG="no"
python3.11 huawei2mqtt.py &