/*
 * CHESS data for the HVAC / PV data from Aveva-pi
 *
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Text.Json.Serialization;

namespace IO.Swagger.Models
{
    /// <summary>
    /// A CHESS data for PV / HVAC time series data 
    /// </summary>
    [DataContract]
    public partial class CHESSData : IEquatable<CHESSData>
    { 
        /// <summary>
        /// Reference to the Data Element
        /// </summary>
  
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_AL1")]
        public CHESSDataElement[] MRD_GN_UFC_AL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_AL2")]
        public CHESSDataElement[] MRD_GN_UFC_AL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_AL3")]
        public CHESSDataElement[] MRD_GN_UFC_AL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_Hz")]
        public CHESSDataElement[] MRD_GN_UFC_Hz { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_kWh")]
        public CHESSDataElement[] MRD_GN_UFC_kWh { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_PFL1")]
        public CHESSDataElement[] MRD_GN_UFC_PFL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_PFL2")]
        public CHESSDataElement[] MRD_GN_UFC_PFL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_PFL3")]
        public CHESSDataElement[] MRD_GN_UFC_PFL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_PFsys")]
        public CHESSDataElement[] MRD_GN_UFC_PFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_VFFsys")]
        public CHESSDataElement[] MRD_GN_UFC_VFFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_WL1")]
        public CHESSDataElement[] MRD_GN_UFC_WL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_WL2")]
        public CHESSDataElement[] MRD_GN_UFC_WL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_WL3")]
        public CHESSDataElement[] MRD_GN_UFC_WL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-UFC_Wsys")]
        public CHESSDataElement[] MRD_GN_UFC_Wsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_AL1")]
        public CHESSDataElement[] MRD_GN_CDZ_AL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_AL2")]
        public CHESSDataElement[] MRD_GN_CDZ_AL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_AL3")]
        public CHESSDataElement[] MRD_GN_CDZ_AL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_Hz")]
        public CHESSDataElement[] MRD_GN_CDZ_Hz { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_kWh")]
        public CHESSDataElement[] MRD_GN_CDZ_kWh { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_PFL1")]
        public CHESSDataElement[] MRD_GN_CDZ_PFL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_PFL2")]
        public CHESSDataElement[] MRD_GN_CDZ_PFL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_PFL3")]
        public CHESSDataElement[] MRD_GN_CDZ_PFL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_PFsys")]
        public CHESSDataElement[] MRD_GN_CDZ_PFLsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_VFFsys")]
        public CHESSDataElement[] MRD_GN_CDZ_VFFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_WL1")]
        public CHESSDataElement[] MRD_GN_CDZ_WL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_WL2")]
        public CHESSDataElement[] MRD_GN_CDZ_WL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_WL3")]
        public CHESSDataElement[] MRD_GN_CDZ_WL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_CDZ_Wsys")]
        public CHESSDataElement[] MRD_GN_CDZ_Wsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_AL1")]
        public CHESSDataElement[] MRD_GN_CK_AL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_AL2")]
        public CHESSDataElement[] MRD_GN_CK_AL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_AL3")]
        public CHESSDataElement[] MRD_GN_CK_AL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_Hz")]
        public CHESSDataElement[] MRD_GN_CK_Hz { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_kWh")]
        public CHESSDataElement[] MRD_GN_CK_kWh { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_PFL1")]
        public CHESSDataElement[] MRD_GN_CK_PFL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_PFL2")]
        public CHESSDataElement[] MRD_GN_CK_PFL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_PFL3")]
        public CHESSDataElement[] MRD_GN_CK_PFL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_PFsys")]
        public CHESSDataElement[] MRD_GN_CK_PFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_VFFsys")]
        public CHESSDataElement[] MRD_GN_CK_VFFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_WL1")]
        public CHESSDataElement[] MRD_GN_CK_WL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_WL2")]
        public CHESSDataElement[] MRD_GN_CK_WL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_WL3")]
        public CHESSDataElement[] MRD_GN_CK_WL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRD_GN-CK_Wsys")]
        public CHESSDataElement[] MRD_GN_CK_Wsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_AL1")]
        public CHESSDataElement[] MRC_GN_GN_AL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_AL2")]
        public CHESSDataElement[] MRC_GN_GN_AL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_AL3")]
        public CHESSDataElement[] MRC_GN_GN_AL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_Hz")]
        public CHESSDataElement[] MRC_GN_GN_Hz { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_kWh")]
        public CHESSDataElement[] MRC_GN_GN_kWh { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_PFL1")]
        public CHESSDataElement[] MRC_GN_GN_PFL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_PFL2")]
        public CHESSDataElement[] MRC_GN_GN_PFL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_PFL3")]
        public CHESSDataElement[] MRC_GN_GN_PFL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_PFsys")]
        public CHESSDataElement[] MRC_GN_GN_PFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_VFFsys")]
        public CHESSDataElement[] MRC_GN_GN_VFFsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_WL1")]
        public CHESSDataElement[] MRC_GN_GN_WL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_WL2")]
        public CHESSDataElement[] MRC_GN_GN_WL2 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_WL3")]
        public CHESSDataElement[] MRC_GN_GN_WL3 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_GN_Wsys")]
        public CHESSDataElement[] MRC_GN_GN_Wsys { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_AL1")]
        public CHESSDataElement[] MRC_GN_CDZ_AL1 { get; set; }
        [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_AL2")]
	    public CHESSDataElement[] MRC_GN_CDZ_AL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_AL3")]
	    public CHESSDataElement[] MRC_GN_CDZ_AL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_Hz")]
	    public CHESSDataElement[] MRC_GN_CDZ_Hz { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_kWh")]
	    public CHESSDataElement[] MRC_GN_CDZ_kWh { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_PFL1")]
	    public CHESSDataElement[] MRC_GN_CDZ_PFL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_PFL2")]
	    public CHESSDataElement[] MRC_GN_CDZ_PFL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_PFL3")]
	    public CHESSDataElement[] MRC_GN_CDZ_PFL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_PFsys")]
	    public CHESSDataElement[] MRC_GN_CDZ_PFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_VFFsys")]
	    public CHESSDataElement[] MRC_GN_CDZ_VFFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_WL1")]
	    public CHESSDataElement[] MRC_GN_CDZ_WL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_WL2")]
	    public CHESSDataElement[] MRC_GN_CDZ_WL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_WL3")]
	    public CHESSDataElement[] MRC_GN_CDZ_WL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRC_CDZ_Wsys")]
	    public CHESSDataElement[] MRC_GN_CDZ_Wsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_AL1")]
	    public CHESSDataElement[] MRB_GN_A_AL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_AL2")]
	    public CHESSDataElement[] MRB_GN_A_AL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_AL3")]
	    public CHESSDataElement[] MRB_GN_A_AL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_Hz")]
	    public CHESSDataElement[] MRB_GN_A_Hz { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_kWh")]
	    public CHESSDataElement[] MRB_GN_A_kWh { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_PFL1")]
	    public CHESSDataElement[] MRB_GN_A_PFL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_PFL2")]
	    public CHESSDataElement[] MRB_GN_A_PFL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_PFL3")]
	    public CHESSDataElement[] MRB_GN_A_PFL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_PFsys")]
	    public CHESSDataElement[] MRB_GN_A_PFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_VFFsys")]
	    public CHESSDataElement[] MRB_GN_A_VFFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_WL1")]
	    public CHESSDataElement[] MRB_GN_A_WL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_WL2")]
	    public CHESSDataElement[] MRB_GN_A_WL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_WL3")]
	    public CHESSDataElement[] MRB_GN_A_WL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN_A_Wsys")]
	    public CHESSDataElement[] MRB_GN_A_WLsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_AL1")]
	    public CHESSDataElement[] MRB_GN_FV_AL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_AL2")]
	    public CHESSDataElement[] MRB_GN_FV_AL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_AL3")]
	    public CHESSDataElement[] MRB_GN_FV_AL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_Hz")]
	    public CHESSDataElement[] MRB_GN_FV_Hz { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_kWh")]
	    public CHESSDataElement[] MRB_GN_FV_kWh { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_PFL1")]
	    public CHESSDataElement[] MRB_GN_FV_PFL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_PFL2")]
	    public CHESSDataElement[] MRB_GN_FV_PFL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_PFL3")]
	    public CHESSDataElement[] MRB_GN_FV_PFL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_PFsys")]
	    public CHESSDataElement[] MRB_GN_FV_PFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_VFFsys")]
	    public CHESSDataElement[] MRB_GN_FV_VFFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_WL1")]
	    public CHESSDataElement[] MRB_GN_FV_WL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_WL2")]
	    public CHESSDataElement[] MRB_GN_FV_WL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_WL3")]
	    public CHESSDataElement[] MRB_GN_FV_WL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRB_GN-FV_Wsys")]
	    public CHESSDataElement[] MRB_GN_FV_Wsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_AL1")]
	    public CHESSDataElement[] MRA_P8_CDZ_AL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_AL2")]
	    public CHESSDataElement[] MRA_P8_CDZ_AL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_AL3")]
	    public CHESSDataElement[] MRA_P8_CDZ_AL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_Hz")]
	    public CHESSDataElement[] MRA_P8_CDZ_Hz { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_kWh")]
	    public CHESSDataElement[] MRA_P8_CDZ_kWh { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_PFL1")]
	    public CHESSDataElement[] MRA_P8_CDZ_PFL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_PFL2")]
	    public CHESSDataElement[] MRA_P8_CDZ_PFL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_PFL3")]
	    public CHESSDataElement[] MRA_P8_CDZ_PFL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_PFsys")]
	    public CHESSDataElement[] MRA_P8_CDZ_PFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_VFFsys")]
	    public CHESSDataElement[] MRA_P8_CDZ_VFFsys { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_WL1")]
	    public CHESSDataElement[] MRA_P8_CDZ_WL1 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_WL2")]
	    public CHESSDataElement[] MRA_P8_CDZ_WL2 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_WL3")]
	    public CHESSDataElement[] MRA_P8_CDZ_WL3 { get; set; }
	    [DataMember(Name="EDMS_SD_MRT_MRA_P8-CDZ_Wsys")]
	    public CHESSDataElement[] MRA_P8_CDZ_Wsys { get; set; } 



      

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CHESSData)obj);
        }

        /// <summary>
        /// Returns true if CHESSData instances are equal
        /// </summary>
        /// <param name="other">Instance of CHESSData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CHESSData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return false;
              
        }


        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CHESSData left, CHESSData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CHESSData left, CHESSData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
